[package]
name = "dominant_colours"
version = "1.1.8"
edition = "2018"

[dependencies]
assert_cmd = "2.0.14"
clap = "4.0.18"

[dependencies.kmeans_colors]
version = "0.6.0"
features = ["palette_color"]
default-features = false

[dependencies.image]
version = "0.24"
features = ["jpeg", "png", "gif", "tiff"]
default-features = false

[dependencies.palette]
version = "0.6"
default-features = false
features = ["std"]
